# -*- coding: utf-8 -*-
"""24022026.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C6ZCJa7VAhn97l5jKexIt6a-8HWFS86j
"""

deli = 'kishore'
def order():
  item1 = 'idly'
  def item():
      idly = '1'
      print(f"order {idly} {item1} {deli}")
  item()
order()

amount = 1200
tax = amount * 0.18
total = tax + amount
print(total)
if total>1000:
  discount = total*0.1
  total -= discount
print(total)

import sys

if len(sys.argv)==2:
  print ("fullname")
  sys.exit()

# You can enter a name here. For example:
# name = 'John Doe' # Change this to the name you want to use

# If you were running this as a command-line script, you would use sys.argv[1]
# For example: python your_script.py "John Doe"
name = sys.argv[1]

email = name.lower().replace(' ', '.') + 'companyname.com'

print(email)



for i in range(10):
  if i ==5:
    break
  print(i)

rk =[1, -2, 3,-1, 0]
for i in rk:
  if i <=0:
    continue
  print(i)

items =[]

while True:
 item = input("input done ")
 if item.lower() == "done":
  break
 items.append(item)
print(items)

def func_name()
 #code logic

def tes():
  print('welcome')

tes()

#function with argument
def test(name):
 print(f"hello {name}")

name= 'kishore'
test(name)

"""Method vs Functions

funtion is a block fo reusable code
anything which ends with () is a function
The return statement in Python is used inside a function to send a value back to the code that called it and to immediately stop the function's execution
"""

def add(a,b):
  return(a+b)
result = add(1,2)
print(result)

def cal(*args):
  total =0
  for num in args:
    total += num
  return total

print(cal(1, 3))

def profile(**kwargs):
  for key, value in kwargs.items():
    print(f'{key} , {value} ')
profile(name="kishore", std="10th")